/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Constaint.TitleConstants;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author datbu
 */
public class LoadingProcess extends javax.swing.JFrame {

    private Timer timer;
    private int progressValue = 0;

    public LoadingProcess(Class<? extends JFrame> nextFrameClass) {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setTitle(TitleConstants.LOADING_PROCESS_TITLE);
        startLoading(nextFrameClass);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void startLoading(Class<? extends JFrame> nextFrameClass) {
        timer = new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (progress.getValue() < progress.getMaximum()) {
                    progressValue++;
                    progress.setValue(progressValue);
                } else {
                    timer.stop();
                    dispose();
                    try {
                        // Tạo frame mới từ class được truyền vào
                        JFrame frame = nextFrameClass.getDeclaredConstructor().newInstance();
                        frame.setVisible(true);
                    } catch (InvocationTargetException ei) {
                        ei.getTargetException().printStackTrace(); // lỗi thật sự nằm ở đây
                    } catch (Exception el) {
                        el.printStackTrace();
                    }
                }
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        progress.setBackground(new java.awt.Color(153, 255, 102));
        progress.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        progress.setForeground(new java.awt.Color(51, 255, 51));
        progress.setMaximum(200);
        progress.setMinimumSize(new java.awt.Dimension(30, 14));
        progress.setPreferredSize(new java.awt.Dimension(146, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
