/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.GradeDao;
import DAO.StudentsDAO;
import DAO.UsersDAO;
import MODEL.Students;
import MODEL.Grade;
import MODEL.Users;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

//
import org.apache.poi.ss.formula.functions.Columns;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class QuanLiDiemSV extends javax.swing.JFrame {

    GradeDao gradeDao = new GradeDao();
    StudentsDAO stuDAO = new StudentsDAO();
    UsersDAO useDao=new UsersDAO();
    List<Grade> listGrade = new ArrayList<>();
    int idx = 0;
    private String[] header = {"Mã SV", "Tên Sinh Viên", "Tiếng Anh", "Tin Học", "Giáo Dục Thể Chất", "DTB"};
    private DefaultTableModel mode = new DefaultTableModel(header, 0);

    /**
     * Creates new form QuanLiDiemSV
     */
    public QuanLiDiemSV() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("From Quản Lí Điểm Của Giảng Viên");
        loadFromGrade();
        loadDSDiemCao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblQuanLiSinhVien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblMaSV_Search = new javax.swing.JLabel();
        txtMaSV_Search = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnFist = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblHoVaTen = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        lblMaSV = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTiengAnh = new javax.swing.JTextField();
        lblTinHoc = new javax.swing.JLabel();
        txtTinHoc = new javax.swing.JTextField();
        txtGiaoDucTC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblDiemTB = new javax.swing.JLabel();
        txtDiemTrungBinh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDSDiemCao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        lblQuanLiSinhVien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblQuanLiSinhVien.setForeground(new java.awt.Color(255, 102, 102));
        lblQuanLiSinhVien.setText("QUẢN LÍ ĐIỂM SINH VIÊN");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        lblMaSV_Search.setText("MÃ SV:");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaSV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaSV_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaSV_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSV_Search)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        jLabel10.setText("3 Sinh viên cao điểm nhất lớp");

        btnFist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/First.png"))); // NOI18N
        btnFist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFistActionPerformed(evt);
            }
        });

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/back.png"))); // NOI18N
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/next.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Last.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFist, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/new_mail_accept.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/save.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/e.png"))); // NOI18N
        btnExel.setText("ExportExcel");
        btnExel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHoVaTen.setText("HỌ VÀ TÊN");

        lblMaSV.setText("MÃ SV:");

        jLabel6.setText("Tiếng Anh");

        txtTiengAnh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTiengAnhKeyTyped(evt);
            }
        });

        lblTinHoc.setText("Tin Học");

        txtTinHoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTinHocKeyTyped(evt);
            }
        });

        txtGiaoDucTC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiaoDucTCKeyTyped(evt);
            }
        });

        jLabel8.setText("Giáo Dục TC: ");

        lblDiemTB.setText("Điểm TB:");

        txtDiemTrungBinh.setText("9.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTinHoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtMaSV)
                    .addComponent(txtTiengAnh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTinHoc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDiemTB, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(txtDiemTrungBinh))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTiengAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTinHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaoDucTC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiemTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tblDSDiemCao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaSV", "HoTen", "TiengAnh", "TinHoc", "GDTC", "DiemTB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSDiemCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDSDiemCaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDSDiemCao);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(lblQuanLiSinhVien))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuanLiSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFistActionPerformed
        goFirst();
        // tblDSDiemCao.setRowSelectionInterval(idx, idx);
    }//GEN-LAST:event_btnFistActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        goLast();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int choose = JOptionPane.showConfirmDialog(this, "Ban co muon xoa khong?");
        if (choose == JOptionPane.YES_OPTION) {
            delete(txtMaSV.getText());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDSDiemCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDSDiemCaoMouseClicked
        readFromTable();
    }//GEN-LAST:event_tblDSDiemCaoMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String maSV = txtMaSV_Search.getText();
        timSV(maSV);
        DiemTB();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        saveGrade();
        String text = btnSave.getText();
        if (text.equalsIgnoreCase("save")) {
            btnSave.setText("UPDATE");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        txtTiengAnh.setText("");
        txtGiaoDucTC.setText("");
        txtTinHoc.setText("");
        txtDiemTrungBinh.setText("");
        txtTiengAnh.requestFocus();
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtTiengAnhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTiengAnhKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) & evt.getKeyChar() != KeyEvent.VK_PERIOD) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTiengAnhKeyTyped

    private void txtTinHocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTinHocKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) & evt.getKeyChar() != KeyEvent.VK_PERIOD) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTinHocKeyTyped

    private void txtGiaoDucTCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaoDucTCKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) & evt.getKeyChar() != KeyEvent.VK_PERIOD) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGiaoDucTCKeyTyped

    private void btnExelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExelActionPerformed
        // TODO add your handling code here:
        XuatFileExcel();
    }//GEN-LAST:event_btnExelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiDiemSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiDiemSV().setVisible(true);
            }
        });
    }

    public void XuatFileExcel() {
       // Workbook workbook = new XSSFWorkbook();
       Workbook workbook = new XSSFWorkbook();
//        Tao sheet
        Sheet sheet = workbook.createSheet("GRADE");
//        Trang tri mot ti font
        Font headerFont = workbook.createFont();
        headerFont.setBold(true);
        headerFont.setFontHeightInPoints((short) 14);
        headerFont.setColor(IndexedColors.BLUE.getIndex());
        //     Cung la trang tri tiep       
        CellStyle headerStyle = workbook.createCellStyle();
        headerStyle.setFont(headerFont);
//      Tao mot dong chua tieu de cac cot
       
        Row headerRow = sheet.createRow(0);
//      Tao  cot
        for (int i = 0; i < header.length; i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(header[i]);
            cell.setCellStyle(headerStyle);
        }
        //

        int rowNum = 1;
        Connection con = null;
        Statement st = null;
        ResultSet rs = null;
        String url = "jdbc:sqlserver://localhost:1433;databaseName=QuanLiSV;user=sa;password=thaoly";
        try {
            con = DriverManager.getConnection(url);
            String sql = " select G.MASV, S.Hoten, G.TiengAnh, G.TinHoc, G.GDTC, round((tienganh+tinhoc+gdtc)/3,2) as DTB"
                    + " from GRADE G join students S ON G.MASV = S.MASV ";
            java.sql.Statement stm = con.createStatement();
            rs = stm.executeQuery(sql);
            Vector vt = null;
            while (rs.next()) {
                vt = new Vector();
                vt.add(rs.getString("MASV"));
                vt.add(rs.getString("Hoten"));
                vt.add(rs.getString("TiengAnh"));
                vt.add(rs.getString("TinHoc"));
                vt.add(rs.getString("GDTC"));
                vt.add(rs.getString("DTB"));

               Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(rs.getString("MaSV"));
                row.createCell(1).setCellValue(rs.getString("Hoten"));
                row.createCell(2).setCellValue(rs.getString("TiengAnh"));
                row.createCell(3).setCellValue(rs.getString("TinHoc"));
                row.createCell(4).setCellValue(rs.getString("GDTC"));
                row.createCell(5).setCellValue(rs.getString("DTB"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
//        
//
//
//
//////////////////////////
   
   
        try {
            FileOutputStream fos = new FileOutputStream("GRADE1.xlsx");
            JOptionPane.showMessageDialog(rootPane, "Xuất Thành Công");
            workbook.write(fos);
            fos.close();
            workbook.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExel;
    private javax.swing.JButton btnFist;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JLabel lblHoVaTen;
    private javax.swing.JLabel lblMaSV;
    private javax.swing.JLabel lblMaSV_Search;
    private javax.swing.JLabel lblQuanLiSinhVien;
    private javax.swing.JLabel lblTinHoc;
    private javax.swing.JTable tblDSDiemCao;
    private javax.swing.JTextField txtDiemTrungBinh;
    private javax.swing.JTextField txtGiaoDucTC;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtMaSV_Search;
    private javax.swing.JTextField txtTiengAnh;
    private javax.swing.JTextField txtTinHoc;
    // End of variables declaration//GEN-END:variables

    public void loadFromGrade() {
        listGrade = gradeDao.getAll(); // lay het bang diem tu DTB len
        // sau do do thong tin cua SV dau tien len cac textfield:
        fillInfo(listGrade.get(0));
        DiemTB();
    }

    public void goFirst() {
        idx = 0;
        fillInfo(listGrade.get(0));
    }

    public void goLast() {
        idx = listGrade.size() - 1;
        fillInfo(listGrade.get(idx));
    }

    public void fillInfo(Grade grade) { // do du lieu len textfield
        txtMaSV.setText(grade.getMaSV());
        txtTiengAnh.setText(grade.getTiengAnh() + "");
        txtTinHoc.setText(grade.getTinHoc() + "");
        txtGiaoDucTC.setText(grade.getGDTC() + "");
        Students st = stuDAO.findById(grade.getMaSV());
        txtHoVaTen.setText(st.getHoTen());
        DiemTB();
    }

    public void next() {
        if (idx == listGrade.size() - 1) { // neu idx da o cuoi cung roi thi xuat thong bao
            JOptionPane.showMessageDialog(this, "Dang o cuoi danh sach");
        } else {
            idx++;
            fillInfo(listGrade.get(idx));
        }
    }

    public void prev() {
        if (idx == 0) {
            JOptionPane.showMessageDialog(this, "Dang o dau danh sach");
        } else {
            idx--;
            fillInfo(listGrade.get(idx));
        }
    }

    public void timSV(String maSV) {
        Students stu = stuDAO.findById(maSV);
        if (stu != null) {
            txtHoVaTen.setText(stu.getHoTen());
            txtMaSV.setText(stu.getMaSV());
            /*
                xet doi tuong SV vua tim duoc co ton tai trong bang diem (GRADE) hay khong?
                    --> neu co ton tai thi lay diem 3 cot dua len cac textfield
                    --> neu khong ton tai thi auto set 3 cot diem la 0 0 0
             */
            Grade grade = gradeDao.findByMaSV(stu.getMaSV());
            if (grade != null) {
                btnSave.setText("UPDATE");
                txtTiengAnh.setText(grade.getTiengAnh() + "");
                txtTinHoc.setText(grade.getTinHoc() + "");
                txtGiaoDucTC.setText(grade.getGDTC() + "");
                // vong for nay dung de gan index cho cac button next/prev/...
                for (int i = 0; i < listGrade.size(); i++) {
                    if (grade.getID() == listGrade.get(i).getID()) {
                        idx = i;
                        break;
                    }
                }
            } else {
                // ..........
                btnSave.setText("SAVE");
                txtTiengAnh.setText("0");
                txtTinHoc.setText("0");
                txtGiaoDucTC.setText("0");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sinh vien khong ton tai!!!");
        }
    }

    public void saveGrade() {
        Grade grade = gradeDao.findByMaSV(txtMaSV.getText());
        if (grade != null) { // truong hop bang diem da ton tai masv
            if (checkDiem(txtTiengAnh.getText()) && checkDiem(txtTinHoc.getText()) && checkDiem(txtGiaoDucTC.getText())) {
                grade.setTiengAnh(Float.parseFloat(txtTiengAnh.getText()));
                grade.setTinHoc(Float.parseFloat(txtTinHoc.getText()));
                grade.setGDTC(Float.parseFloat(txtGiaoDucTC.getText()));
                boolean result = gradeDao.update(grade);
                if (result) {
                    JOptionPane.showMessageDialog(this, "Luu thanh cong!!!");
                    listGrade = gradeDao.getAll(); // lay het bang diem tu DTB len
                } else {
                    JOptionPane.showMessageDialog(this, "Luu that bai!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Kiem tra lai diem!!!");
            }

        } else { // neu khong ton tai thi insert
            Grade insertGrade = new Grade();
            insertGrade.setMaSV(txtMaSV.getText());
            insertGrade.setTiengAnh(Float.parseFloat(txtTiengAnh.getText()));
            insertGrade.setTinHoc(Float.parseFloat(txtTinHoc.getText()));
            insertGrade.setGDTC(Float.parseFloat(txtGiaoDucTC.getText()));
            boolean result = gradeDao.insert(insertGrade);
            if (result) {
                JOptionPane.showMessageDialog(this, "Luu thanh cong!!!");
                listGrade = gradeDao.getAll(); // lay het bang diem tu DTB len
            } else {
                JOptionPane.showMessageDialog(this, "Luu that bai!!!");
            }
            idx = listGrade.size() - 1;
        }
        DiemTB();
        loadDSDiemCao();
    }

    public void DiemTB() {
        Float diemTiengAnh = Float.parseFloat(txtTiengAnh.getText());
        Float diemTinHoc = Float.parseFloat(txtTinHoc.getText());
        Float diemGDTC = Float.parseFloat(txtGiaoDucTC.getText());
        DecimalFormat dmf = new DecimalFormat("##.00");
        txtDiemTrungBinh.setText(dmf.format((diemTiengAnh + diemGDTC + diemTinHoc) / 3));
    }

    public void delete(String maSV) {
        Grade grade = gradeDao.findByMaSV(maSV);
        grade.setTiengAnh(-1);
        grade.setTinHoc(-1);
        grade.setGDTC(-1);
        boolean result = gradeDao.update(grade);
        if (result) {
            JOptionPane.showMessageDialog(this, "Xoa thanh cong!!!");
            listGrade = gradeDao.getAll(); // lay het bang diem tu DTB len
            fillInfo(listGrade.get(idx));
            DiemTB();
            loadDSDiemCao();
        } else {
            JOptionPane.showMessageDialog(this, "Xoa that bai!!!");
        }
    }

    public void loadDSDiemCao() {
        DefaultTableModel dtm = (DefaultTableModel) tblDSDiemCao.getModel();
        List<Object[]> listDiemCao = gradeDao.sortByMark();
        dtm.setRowCount(0);
        for (Object[] row : listDiemCao) {
            dtm.addRow(row);
        }
    }

    // ham nay load du lieu sinh vien duoc chon tu table diem cao len cac textfield
    public void readFromTable() {
        int row = tblDSDiemCao.getSelectedRow();
        String maSV = tblDSDiemCao.getValueAt(row, 0).toString(); // 0: la cot MaSV
        Grade grade = gradeDao.findByMaSV(maSV);
        fillInfo(grade);
        // cap nhat lai index:
        for (int i = 0; i < listGrade.size(); i++) {
            if (grade.getID() == listGrade.get(i).getID()) {
                idx = i;
                break;
            }
        }
    }

    public boolean checkDiem(String strDiem) {
        try {
            float diemTA = Float.parseFloat(strDiem);
            if (diemTA < 0 || diemTA > 10) {
                return false;
            } else {
                return true;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }
}
