/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DAO.Impl;
import DAO.TeacherDAO;
import MODEL.Teacher;
import com.oracle.wls.shaded.org.apache.bcel.generic.AALOAD;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import javax.imageio.ImageIO;
/**
 *
 * @author ADMIN
 */
public class BlobToButtonExample extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
public BlobToButtonExample() throws IOException {
    Teacher t = TeacherDAO.getInstance().findById(37L); // lấy ra teacher
    byte[] by = t.getImg(); // giả sử cột ảnh là byte[] (BLOB)

    // Debug xem BLOB có dữ liệu không
    System.out.println("BLOB length = " + (by != null ? by.length : 0));
    System.out.println("t.getImg() length = " + (t.getImg() != null ? t.getImg().length : 0));

    JButton btn;
    if (by != null) {
        BufferedImage img = ImageIO.read(new ByteArrayInputStream(by));
        if (img != null) {
            btn = new JButton(new ImageIcon(img)); // set Icon cho JButton
        } else {
            btn = new JButton("Ảnh không hợp lệ");
        }
    } else {
        btn = new JButton("Không có ảnh");
    }

    JFrame frame = new JFrame("BLOB to JButton");
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.add(btn);
    frame.pack();
    frame.setVisible(true);

//add();
}
private void add(){
    Teacher t = new Teacher();
    t.setEmail("email");    t.setName("123");

    TeacherDAO.getInstance().insertTeacherWithImage(t, "C:\\Users\\ADMIN\\Pictures\\background\\123.jpg");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            try {
                new BlobToButtonExample().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(BlobToButtonExample.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
