/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.admin.popup;

import DAO.UsersDAO;
import DAO.StudentsDAO;
import DAO.TeacherDAO;
import MODEL.Users;
import MODEL.Student;
import MODEL.Teacher;
import Utils.tableFillingUtils;
import Utils.validationUtils;
import Constaint.TitleConstants;
import GUI.admin.popup.search.SearchStudentDialog;
import GUI.admin.popup.search.SearchTeacherDialog;
import java.time.LocalDate;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class UserDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserDialog.class.getName());
    private final JTable table;
    private final Long ID;
    private String previousRole;

    public UserDialog(java.awt.Frame parent, boolean modal, Users user, JTable t) {
        super(parent, modal);
        initComponents();
        table = t;
        fillForm(user);
        ID = Objects.nonNull(user) ? user.getId() : null;
        previousRole = (String) roleComboBox.getSelectedItem();
        updateEmailFieldState(); // Ensure initial state is set correctly
        setTitle(TitleConstants.USER_MANAGEMENT_TITLE); // Use the constant here
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        nameLabel1 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        nameLabel2 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        roleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(100, 30));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm mới");
        btnAdd.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        nameLabel1.setText("ID");

        idTxt.setEditable(false);
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        emailTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailTxtMousePressed(evt);
            }
        });

        nameLabel2.setText("Email");

        usernameLabel.setText("Tên đăng nhập:");

        roleLabel.setText("Vai trò:");

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản trị viên", "Giáo viên", "Sinh viên" }));
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String currentRole = (String) roleComboBox.getSelectedItem();
        if (currentRole == null) {
            return;
        }

        if (!emailTxt.getText().isEmpty() && !currentRole.equals(previousRole)) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "User của bạn đang được liên kết với hồ sơ, hồ sơ liên kết sẽ bị xóa hết thay đổi, bạn vẫn tiếp tục chứ ?",
                    "Xác nhận thay đổi",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.NO_OPTION) {
                roleComboBox.setSelectedItem(previousRole);
                updateEmailFieldState();
                return;
            } else {
                emailTxt.setText("");
            }
        }
        updateEmailFieldState();
        previousRole = currentRole;
    }                                            

    private void emailTxtMousePressed(java.awt.event.MouseEvent evt) {
        String selectedRole = (String) roleComboBox.getSelectedItem();
        if (!emailTxt.isEditable()) {
            if ("Giáo viên".equals(selectedRole)) {
                SearchTeacherDialog dialog = new SearchTeacherDialog((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true, emailTxt);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
            } else if ("Sinh viên".equals(selectedRole)) {
                SearchStudentDialog dialog = new SearchStudentDialog((java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this), true, emailTxt);
                dialog.setLocationRelativeTo(this);
                dialog.setVisible(true);
            }
        }
    }

    private void updateEmailFieldState() {
        String selectedRole = (String) roleComboBox.getSelectedItem();
        if ("Quản trị viên".equals(selectedRole)) {
            emailTxt.setEditable(true);
        } else if ("Giáo viên".equals(selectedRole) || "Sinh viên".equals(selectedRole)) {
            emailTxt.setEditable(false);
        }
    }

    private void fillForm(Users user) {
        if (user == null) {
            return;
        }
        btnAdd.setText("Sửa");
        idTxt.setText(user.getId().toString());
        emailTxt.setText(user.getEmail());
        usernameTxt.setText(user.getUsername());
        roleComboBox.setSelectedIndex(user.getRole());
//        isDeletedCheckBox.setSelected(user.isIsDeleted());
        updateEmailFieldState(); // Update state after filling form
    }

    private void create() {
        UsersDAO.getInstance().add(getData());
        JOptionPane.showMessageDialog(this,
                "Tạo người dùng thành công!",
                "Thông báo",
                JOptionPane.INFORMATION_MESSAGE
        );
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.insertRow(0, tableFillingUtils.fillUser(getData()));
    }

    private void update() {
        UsersDAO.getInstance().update(getData());
        JOptionPane.showMessageDialog(this,
                "Cập nhật người dùng thành công!",
                "Thông báo",
                JOptionPane.INFORMATION_MESSAGE
        );
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.removeRow(table.getSelectedRow());
        model.insertRow(0, tableFillingUtils.fillUser(getData()));
    }

    private Users getData() {
        Users user = new Users();
        user.setId(idTxt.getText().isEmpty() ? null : Long.valueOf(idTxt.getText()));
        String selectedRole = (String) roleComboBox.getSelectedItem();
        String email = emailTxt.getText();
        if ("Giáo viên".equals(selectedRole)) {
            int dashIndex = email.indexOf(" - ");
            if (dashIndex != -1) {
                Long teacherId = Long.valueOf(email.substring(0, dashIndex));
                Teacher teacher = TeacherDAO.getInstance().findById(teacherId);
                if (teacher != null) {
                    email = teacher.getEmail();
                }
            }
        } else if ("Sinh viên".equals(selectedRole)) {
            int dashIndex = email.indexOf(" - ");
            if (dashIndex != -1) {
                Long studentId = Long.valueOf(email.substring(0, dashIndex));
                Student student = StudentsDAO.getInstance().findById(studentId);
                if (student != null) {
                    email = student.getEmail();
                }
            }
        }
        user.setEmail(email);
        user.setUsername(usernameTxt.getText());
        user.setRole((byte) roleComboBox.getSelectedIndex());

        return user;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTxt;
 


    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {
        idTxt.setText("");
        emailTxt.setText("");
        usernameTxt.setText("");
        roleComboBox.setSelectedIndex(0);
        updateEmailFieldState();
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        if (Objects.isNull(ID)) {
            this.create();
        } else {
            this.update();
        }
        this.dispose();
    }

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
       // End of variables declaration//GEN-END:variables
}
